apiVersion: v1
kind: Secret
metadata:
  name: {{ include "uno.secretName" . }}
  labels:
    {{- include "uno.labels" . | nindent 4 }}
type: Opaque
data:
  db-username: {{ .Values.config.db.username | b64enc | quote }}
  db-password: {{ .Values.config.db.password | b64enc | quote }}
  clickhouse-username: {{ .Values.config.clickhouse.username | b64enc | quote }}
  clickhouse-password: {{ .Values.config.clickhouse.password | default "" | b64enc | quote }}

